
#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include <s2/s2earth.h>
#include <s2/s2point.h>
#include <s2/s2polyline.h>

#include <cstdlib>
#include <fstream>
#include <regex>
#include <thread>
#include <variant>

#include "../util/GTestHelpers.h"
#include "../util/IndexTestHelpers.h"
#include "../util/RuntimeParametersTestHelpers.h"
#include "TensorIndexTestHelpers.h"
#include "TensorTestHelpers.h"
#include "engine/ExportQueryExecutionTrees.h"
#include "engine/IndexScan.h"
#include "engine/QueryExecutionTree.h"
#include "engine/TensorIndex.h"
#include "engine/TensorIndexConfig.h"
#include "engine/TensorIndexCachedIndex.h"
#include "index/vocabulary/VocabularyType.h"
#include "libqlever/Qlever.h"
#include "parser/SparqlParser.h"
#include "rdfTypes/Variable.h"
namespace {  // anonymous namespace to avoid linker problems
using namespace TensorIndexTestHelpers;
using namespace ad_utility::testing;

namespace variableColumnMapAndResultWidth {

// Represents from left to right: leftSideBigChild, rightSideBigChild,
// addLeftChildFirst, testVarToColMap
using VarColTestSuiteParam = std::tuple<bool, bool, bool, bool>;

// Internal testing shorthands
using V = Variable;
using VarToColVec = std::vector<std::pair<V, ColumnIndexAndTypeInfo>>;
// Helper function to create a tensor search from VALUEs
std::shared_ptr<TensorIndex> makeTensorIndexFromValues(
    QueryExecutionContext* qec, PayloadVariables pv = PayloadVariables::all(),
    TensorIndexAlgorithm alg = TENSOR_INDEX_DEFAULT_ALGORITHM) {
  EncodedIriManager encodedIriManager;
  const auto sharedHandle =
      std::make_shared<ad_utility::CancellationHandle<>>();
  // also include some garbage input geometries
  auto pqLeft = SparqlParser::parseQuery(
      &encodedIriManager,
      R"(PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
      SELECT ?a {VALUES 
      (?a) {("{\"data\":[1.0,0,0],\"shape\":[3],\"type\":\"float32\"}"^^dt:DataTensor)}})");
  auto pqRight = SparqlParser::parseQuery(
      &encodedIriManager,
      R"(PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
      SELECT ?b {VALUES
      (?b) {("{\"data\":[0,1.0,0],\"shape\":[3],\"type\":\"float32\"}"^^dt:DataTensor)}})");
  QueryPlanner qp{qec, sharedHandle};

  auto leftChild =
      std::make_shared<QueryExecutionTree>(qp.createExecutionTree(pqLeft));
  auto rightChild =
      std::make_shared<QueryExecutionTree>(qp.createExecutionTree(pqRight));

  std::shared_ptr<QueryExecutionTree> tensorIndexOperation =
      ad_utility::makeExecutionTree<TensorIndex>(
          qec,
          TensorIndexConfiguration{Variable{"?a"}, Variable{"?b"},
                                    std::nullopt, pv, alg},
          std::nullopt, std::nullopt);
  std::shared_ptr<Operation> op = tensorIndexOperation->getRootOperation();
  TensorIndex* tensorIndex = static_cast<TensorIndex*>(op.get());
  auto tensorIndex1 = tensorIndex->addChild(leftChild, Variable{"?a"});
  tensorIndex = static_cast<TensorIndex*>(tensorIndex1.get());
  auto tensorIndex2 = tensorIndex->addChild(rightChild, Variable{"?b"});
  return tensorIndex2;
}

class TensorIndexVarColParamTest
    : public ::testing::TestWithParam<VarColTestSuiteParam> {
 public:
  // Helper function to construct a child for testing
  std::shared_ptr<QueryExecutionTree> getChild(QueryExecutionContext* qec,
                                               bool getBigChild,
                                               std::string numberOfChild) {
    std::string obja = absl::StrCat("?obja", numberOfChild);
    std::string objb = absl::StrCat("?objb", numberOfChild);
    std::string name = absl::StrCat("?name", numberOfChild);
    std::string t = absl::StrCat("?t", numberOfChild);
    if (getBigChild) {
      return buildMediumChild(qec, {obja, std::string{"<name>"}, name},
                              {obja, std::string{"<rel>"}, objb},
                              {objb, std::string{"<p1>"}, t}, obja, objb);
    } else {
      return buildSmallChild(qec, {obja, std::string{"<p1>"}, t},
                             {obja, std::string{"<name>"}, name}, obja);
    }
  }

  // Helper function to construct a vector of the expected columns in the
  // example child generated by getChild
  std::vector<std::pair<std::string, std::string>> addExpectedColumns(
      std::vector<std::pair<std::string, std::string>> expectedColumns,
      bool bigChild, std::string numberOfChild) {
    std::string obja = absl::StrCat("?obja", numberOfChild);
    std::string objb = absl::StrCat("?objb", numberOfChild);
    std::string name = absl::StrCat("?name", numberOfChild);
    std::string t = absl::StrCat("?t", numberOfChild);
    expectedColumns.push_back({obja, "<s"});
    expectedColumns.push_back({name, "\"Name"});
    expectedColumns.push_back({t, "\"{"});
    if (bigChild) {
      expectedColumns.push_back({objb, "<s"});
    }
    return expectedColumns;
  };

  std::shared_ptr<TensorIndex> makeTensorIndex(
      QueryExecutionContext* qec, VarColTestSuiteParam parameters,
      bool addDist = true, PayloadVariables pv = PayloadVariables::all(),
      TensorIndexAlgorithm alg = TENSOR_INDEX_DEFAULT_ALGORITHM,
      TensorDistanceAlgorithm distAlg = TENSOR_INDEX_DEFAULT_DISTANCE) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto leftChild = getChild(qec, leftSideBigChild, "1");
    auto rightChild = getChild(qec, rightSideBigChild, "2");

    std::optional<Variable> dist = std::nullopt;
    if (addDist) {
      dist = Variable{"?dist"};
    }
    std::shared_ptr<QueryExecutionTree> tensorIndexOperation =
        ad_utility::makeExecutionTree<TensorIndex>(
            qec,
            TensorIndexConfiguration{Variable{"?t1"}, Variable{"?t2"}, dist,
                                      pv, alg, distAlg},
            std::nullopt, std::nullopt);
    std::shared_ptr<Operation> op = tensorIndexOperation->getRootOperation();
    TensorIndex* tensorIndex = static_cast<TensorIndex*>(op.get());
    auto firstChild = addLeftChildFirst ? leftChild : rightChild;
    auto secondChild = addLeftChildFirst ? rightChild : leftChild;
    Variable firstVariable =
        addLeftChildFirst ? Variable{"?t1"} : Variable{"?t2"};
    Variable secondVariable =
        addLeftChildFirst ? Variable{"?t2"} : Variable{"?t1"};
    auto tensorIndex1 = tensorIndex->addChild(firstChild, firstVariable);
    tensorIndex = static_cast<TensorIndex*>(tensorIndex1.get());
    auto tensorIndex2 = tensorIndex->addChild(secondChild, secondVariable);
    return tensorIndex2;
  }

  // only test one at a time. Then the gtest will fail on the test, which
  // failed, instead of failing for both getResultWidth() and
  // computeVariableToColumnMap() if only one of them is wrong
  void testGetResultWidthOrVariableToColumnMap(
      VarColTestSuiteParam parameters,
      TensorIndexAlgorithm alg = TENSOR_INDEX_DEFAULT_ALGORITHM) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto qec = buildQec(makeVectorKg(6, 6));
    auto tensorIndexOp =
        makeTensorIndex(qec, parameters, true, PayloadVariables::all(), alg);
    auto tensorIndex = static_cast<TensorIndex*>(tensorIndexOp.get());

    auto numTriples = qec->getIndex().numTriples().normal;
    ASSERT_EQ(numTriples, 17);

    if (!testVarToColMap) {
      size_t expectedResultWidth =
          (leftSideBigChild ? 4 : 3) + (rightSideBigChild ? 4 : 3) + 1;
      ASSERT_EQ(tensorIndex->getResultWidth(), expectedResultWidth);
    } else {
      std::vector<std::pair<std::string, std::string>> expectedColumns{};

      expectedColumns =
          addExpectedColumns(expectedColumns, leftSideBigChild, "1");
      expectedColumns =
          addExpectedColumns(expectedColumns, rightSideBigChild, "2");

      expectedColumns.push_back({"?dist", "0"});

      auto varColMap = tensorIndex->computeVariableToColumnMap();
      auto resultTable = tensorIndex->computeResult(false);

      // if the size of varColMap and expectedColumns is the same and each
      // element of expectedColumns is contained in varColMap, then they are the
      // same (assuming that each element is unique)
      ASSERT_EQ(varColMap.size(), expectedColumns.size());

      for (size_t i = 0; i < expectedColumns.size(); i++) {
        ASSERT_TRUE(varColMap.contains(Variable{expectedColumns.at(i).first}));

        // test, that the column contains the correct values
        ColumnIndex ind =
            varColMap[Variable{expectedColumns.at(i).first}].columnIndex_;
        const IdTable* r = &resultTable.idTable();
        ASSERT_LT(0, r->numRows());
        ASSERT_LT(ind, r->numColumns());
        ValueId tableEntry = r->at(0, ind);

        auto [value, type] = ExportQueryExecutionTrees::idToStringAndType(
                                 qec->getIndex(), tableEntry, {})
                                 .value();
        if (tableEntry.getDatatype() == Datatype::VocabIndex) {
          ASSERT_TRUE(value.find(expectedColumns.at(i).second, 0) !=
                      std::string::npos);
        }
      }
    }
  }

  // Test tensor search on contains
  void testGetResultWidthOrVariableToColumnMapTensorIndexNaive(
      VarColTestSuiteParam parameters) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto qec = buildQec(makeVectorKg(6, 6));

    auto tensorIndex =
        makeTensorIndex(qec, parameters, false, PayloadVariables::all(),
                         TensorIndexAlgorithm::NAIVE,
                         TensorDistanceAlgorithm::COSINE_SIMILARITY);
    auto tensorIndexPtr = static_cast<TensorIndex*>(tensorIndex.get());

    auto numTriples = qec->getIndex().numTriples().normal;
    ASSERT_EQ(numTriples, 17);

    if (!testVarToColMap) {
      size_t expectedResultWidth =
          (leftSideBigChild ? 4 : 3) + (rightSideBigChild ? 4 : 3);
      ASSERT_EQ(tensorIndexPtr->getResultWidth(), expectedResultWidth);
    } else {
      std::vector<std::pair<std::string, std::string>> expectedColumns{};

      expectedColumns =
          addExpectedColumns(expectedColumns, leftSideBigChild, "1");
      expectedColumns =
          addExpectedColumns(expectedColumns, rightSideBigChild, "2");

      auto varColMap = tensorIndexPtr->computeVariableToColumnMap();
      auto resultTable = tensorIndexPtr->computeResult(false);

      // if the size of varColMap and expectedColumns is the same and each
      // element of expectedColumns is contained in varColMap, then they are the
      // same (assuming that each element is unique)
      ASSERT_EQ(varColMap.size(), expectedColumns.size());

      for (size_t i = 0; i < expectedColumns.size(); i++) {
        ASSERT_TRUE(varColMap.contains(Variable{expectedColumns.at(i).first}));

        // test, that the column contains the correct values
        ColumnIndex ind =
            varColMap[Variable{expectedColumns.at(i).first}].columnIndex_;
        const IdTable* r = &resultTable.idTable();
        ASSERT_LT(0, r->numRows());
        ASSERT_LT(ind, r->numColumns());

        auto col = r->getColumn(ind);
        std::vector<std::string> columnEntries;
        columnEntries.reserve(r->numRows());
        for (const auto& valueId : col) {
          auto [value, type] = ExportQueryExecutionTrees::idToStringAndType(
                                   qec->getIndex(), valueId, {})
                                   .value();
          if (type &&
              (type == TENSOR_LITERAL || type == TENSOR_NUMERIC_LITERAL)) {
            value = absl::StrCat("\"", value, "\"^^<", type, ">");
          }
          columnEntries.push_back(value);
        }

        auto expected = expectedColumns.at(i).second;
        EXPECT_THAT(columnEntries,
                    ::testing::Contains(::testing::StartsWith(expected)));
      }
    }
  }

  // Function to test the variable to column map that is generated by tensor
  // search with the left and right children as given by the parameters. It will
  // try all possible, valid payloadVariables settings and check the variable
  // to column maps using a comprehensible and easy to debug string
  // representation.
  void testPayloadVariablesVarToColMap(VarColTestSuiteParam parameters) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    if (!testVarToColMap) {
      return;
    }

    auto computeAndCompareVarToColMaps =
        [&](bool addDist, PayloadVariables pv,
            VariableToColumnMap expectedVarToColMap,
            std::optional<std::string> matchWarning = std::nullopt) {
          auto qec = buildQec(makeVectorKg(6, 6));
          auto tensorIndexOp = makeTensorIndex(qec, parameters, addDist, pv);
          auto tensorIndex = static_cast<TensorIndex*>(tensorIndexOp.get());
          auto vc = tensorIndex->computeVariableToColumnMap();
          // for (const auto& [var, colInfo] : expectedVarToColMap) {
          //   std::cout << "Expecting variable " << var.name() << " in column "
          //             << colInfo.columnIndex_ << "\n";
          // }
          // for (const auto& [var, colInfo] : vc) {
          //   std::cout << "Actual variable " << var.name() << " in column "
          //             << colInfo.columnIndex_ << "\n";
          // }
          ASSERT_THAT(
              vc, ::testing::UnorderedElementsAreArray(expectedVarToColMap));
          if (matchWarning) {
            ASSERT_THAT(tensorIndex->collectWarnings(),
                        ::testing::Contains(
                            ::testing::HasSubstr(matchWarning.value())));
          }
        };

    // Expected variables
    V obja{"?obja"};
    V objb{"?objb"};
    V name{"?name"};
    V distVar{"?dist"};
    std::vector<V> smallChild{obja, name};
    std::vector<V> bigChild{obja, name, objb};

    auto makeExpected = [&](bool leftSideBigChild, bool rightSideBigChild,
                            bool addDist, bool withObja, bool withObjb,
                            bool withName) -> VariableToColumnMap {
      size_t currentColumn = 0;
      VariableToColumnMap expected;

      auto addV = [&](std::vector<V> vec, bool right = false) {
        for (auto v : vec) {
          if (right && ((v == objb && !withObjb) || (v == obja && !withObja) ||
                        (v == name && !withName))) {
            continue;
          }
          V expectedVar{absl::StrCat(v.name(), right ? "2" : "1")};
          expected[expectedVar] = ColumnIndexAndTypeInfo{
              currentColumn,
              ColumnIndexAndTypeInfo::UndefStatus::AlwaysDefined};
          currentColumn++;
        }
      };

      addV(leftSideBigChild ? bigChild : smallChild);
      addV({V{"?t"}});
      addV(rightSideBigChild ? bigChild : smallChild, true);
      addV({V{"?t"}}, true);
      if (addDist) {
        expected[distVar] = ColumnIndexAndTypeInfo{
            currentColumn,
            ColumnIndexAndTypeInfo::UndefStatus::PossiblyUndefined};
      }
      return expected;
    };

    std::vector<bool> bools{true, false};
    for (bool withObja : bools) {
      for (bool withObjb : bools) {
        for (bool withName : bools) {
          for (bool addDist : bools) {
            std::vector<Variable> payloadVars;
            if (withObja) {
              payloadVars.push_back(Variable{"?obja2"});
            }
            if (withObjb && rightSideBigChild) {
              payloadVars.push_back(Variable{"?objb2"});
            }
            if (withName) {
              payloadVars.push_back(Variable{"?name2"});
            }
            // Test the regular and valid payloadVars
            auto exp = makeExpected(leftSideBigChild, rightSideBigChild,
                                    addDist, withObja, withObjb, withName);
            computeAndCompareVarToColMaps(addDist, payloadVars, exp);

            // Also test the PayloadAllVariables version
            if ((withObjb || !rightSideBigChild) && withName && withObja) {
              computeAndCompareVarToColMaps(addDist, PayloadVariables::all(),
                                            exp);
            }

            // Test multiple occurrences of variables
            if (withObjb && rightSideBigChild) {
              payloadVars.push_back(Variable{"?objb2"});
              // Variable ?objb2 is now contained twice
              computeAndCompareVarToColMaps(addDist, payloadVars, exp);
              payloadVars.pop_back();
            }

            // Test contained right variable in payloadVars
            payloadVars.push_back(Variable{"?t2"});
            computeAndCompareVarToColMaps(addDist, payloadVars, exp);
            payloadVars.pop_back();

            // Test warnings for unbound variables
            payloadVars.push_back(Variable{"?t1"});
            computeAndCompareVarToColMaps(
                addDist, payloadVars, exp,
                "Variable '?t1' selected as payload to "
                "tensor search but not present in right child");
            payloadVars.pop_back();

            payloadVars.push_back(Variable{"?obja1"});
            computeAndCompareVarToColMaps(
                addDist, payloadVars, exp,
                "Variable '?obja1' selected as payload to "
                "tensor search but not present in right child");
            payloadVars.pop_back();

            payloadVars.push_back(Variable{"?isThereSomebodyHere"});
            computeAndCompareVarToColMaps(
                addDist, payloadVars, exp,
                "Variable '?isThereSomebodyHere' selected as payload to "
                "tensor search but not present in right child");
            payloadVars.pop_back();

            // Test if distance variable contained
            if (addDist) {
              payloadVars.push_back(distVar);
              computeAndCompareVarToColMaps(
                  addDist, payloadVars, exp,
                  "Variable '?dist' selected "
                  "as payload to tensor search but not present in right "
                  "child");
              payloadVars.pop_back();
            }
          }
        }
      }
    }
  }
};

TEST_P(TensorIndexVarColParamTest, variableToColumnMap) {
  testGetResultWidthOrVariableToColumnMap(GetParam());
}
TEST_P(TensorIndexVarColParamTest, variableToColumnMapLibtensorIndexNaive) {
  testGetResultWidthOrVariableToColumnMapTensorIndexNaive(GetParam());
}

// Test a tensor search with VALUES as both children
TEST(TensorIndexVarColParamTest, testTensorIndexFromvalues) {
  auto qec = buildQec(TensorIndexTestHelpers::makeVectorKg(6, 6));

  auto tensorIndex = makeTensorIndexFromValues(qec, PayloadVariables::all(),
                                                 TensorIndexAlgorithm::NAIVE);
  auto tensorIndex_ptr = static_cast<TensorIndex*>(tensorIndex.get());

  auto resultTable = tensorIndex_ptr->computeResult(false);
  ASSERT_EQ(resultTable.idTable().numRows(), 1);
}

TEST_P(TensorIndexVarColParamTest, payloadVariables) {
  testPayloadVariablesVarToColMap(GetParam());
}

INSTANTIATE_TEST_SUITE_P(TensorIndex, TensorIndexVarColParamTest,
                         ::testing::Combine(::testing::Bool(),
                                            ::testing::Bool(),
                                            ::testing::Bool(),
                                            ::testing::Bool()));

}  // namespace variableColumnMapAndResultWidth

namespace stringRepresentation {
TEST(TensorIndex, getDescriptor) {
  auto qec = getQec();
  TripleComponent subject{Variable{"?subject"}};
  TripleComponent object{Variable{"?object"}};

  std::shared_ptr<QueryExecutionTree> tensorIndexOperation =
      ad_utility::makeExecutionTree<TensorIndex>(
          qec,
          TensorIndexConfiguration{subject.getVariable(),
                                    object.getVariable()},
          std::nullopt, std::nullopt);
  std::shared_ptr<Operation> op = tensorIndexOperation->getRootOperation();
  TensorIndex* tensorIndex = static_cast<TensorIndex*>(op.get());

  auto description = tensorIndex->getDescriptor();
  ASSERT_THAT(description, ::testing::HasSubstr(absl::StrCat(
                               tensorIndex->getMaxResults().value_or(-1))));
  ASSERT_TRUE(description.find("?subject") != std::string::npos);
  ASSERT_TRUE(description.find("?object") != std::string::npos);
}

// _____________________________________________________________________________
TEST(TensorIndex, getDescriptorLibtensorIndexNaive) {
  // The `TensorIndex`'s descriptor should contain a readable representation
  // of the join type
  std::shared_ptr<QueryExecutionTree> tensorIndexOperation =
      ad_utility::makeExecutionTree<TensorIndex>(
          getQec(),
          TensorIndexConfiguration{Variable{"?subject"}, Variable{"?object"},
                                    std::nullopt, PayloadVariables::all(),
                                    TensorIndexAlgorithm::NAIVE,
                                    TensorDistanceAlgorithm::COSINE_SIMILARITY},
          std::nullopt, std::nullopt);
  auto description = tensorIndexOperation->getRootOperation()->getDescriptor();
  ASSERT_THAT(description, ::testing::HasSubstr("?subject"));
  ASSERT_THAT(description, ::testing::HasSubstr("?object"));
  ASSERT_THAT(description, ::testing::HasSubstr("naive"));
  ASSERT_THAT(description, ::testing::HasSubstr("cosine"));
}

// _____________________________________________________________________________
TEST(TensorIndex, getCacheKeyImpl) {
  using namespace TensorIndexTestHelpers;
  auto qec = buildQec(TensorIndexTestHelpers::makeVectorKg(6, 6));
  auto numTriples = qec->getIndex().numTriples().normal;
  ASSERT_EQ(numTriples, 17);
  // ====================== build inputs ===================================
  Variable subj{"?t1"};
  Variable obj{"?t2"};
  auto leftChild =
      buildIndexScan(qec, {"?obj1", std::string{"<hasVector>"}, "?t1"});
  auto rightChild =
      buildIndexScan(qec, {"?obj2", std::string{"<hasVector>"}, "?t2"});

  std::shared_ptr<QueryExecutionTree> tensorIndexOperation =
      ad_utility::makeExecutionTree<TensorIndex>(
          qec, TensorIndexConfiguration{subj, obj}, std::nullopt,
          std::nullopt);
  std::shared_ptr<Operation> op = tensorIndexOperation->getRootOperation();
  TensorIndex* tensorIndex = static_cast<TensorIndex*>(op.get());

  ASSERT_EQ(tensorIndex->getCacheKeyImpl(), "incomplete TensorIndex class");

  auto tensorIndex1 = tensorIndex->addChild(leftChild, subj);
  tensorIndex = static_cast<TensorIndex*>(tensorIndex1.get());

  ASSERT_EQ(tensorIndex->getCacheKeyImpl(), "incomplete TensorIndex class");

  auto tensorIndex2 = tensorIndex->addChild(rightChild, obj);
  tensorIndex = static_cast<TensorIndex*>(tensorIndex2.get());

  auto cacheKeyString = tensorIndex->getCacheKeyImpl();
  auto leftCacheKeyString =
      tensorIndex->onlyForTestingGetLeftChild()->getCacheKey();
  auto rightCacheKeyString =
      tensorIndex->onlyForTestingGetRightChild()->getCacheKey();

  ASSERT_TRUE(cacheKeyString.find(
                  absl::StrCat(tensorIndex->getMaxResults().value_or(-1))) !=
              std::string::npos);
  ASSERT_TRUE(cacheKeyString.find(leftCacheKeyString) != std::string::npos);
  ASSERT_TRUE(cacheKeyString.find(rightCacheKeyString) != std::string::npos);
}

// _____________________________________________________________________________
TEST(TensorIndex, clone) {
  using namespace TensorIndexTestHelpers;
  auto qec = buildQec(TensorIndexTestHelpers::makeVectorKg(6, 6));
  auto numTriples = qec->getIndex().numTriples().normal;
  ASSERT_EQ(numTriples, 17);
  auto leftChild =
      buildIndexScan(qec, {"?obj1", std::string{"<hasVector>"}, "?t1"});
  auto rightChild =
      buildIndexScan(qec, {"?obj2", std::string{"<hasVector>"}, "?t2"});

  {
    TensorIndex tensorIndex{
        qec, TensorIndexConfiguration{Variable{"?t1"}, Variable{"?t2"}},
        std::nullopt, std::nullopt};

    auto clone = tensorIndex.clone();
    ASSERT_TRUE(clone);
    const auto& cloneReference = *clone;
    EXPECT_EQ(typeid(tensorIndex), typeid(cloneReference));
    EXPECT_EQ(cloneReference.getDescriptor(), tensorIndex.getDescriptor());

    EXPECT_EQ(tensorIndex.getChildren().empty(),
              cloneReference.getChildren().empty());
  }

  {
    TensorIndex tensorIndex{
        qec, TensorIndexConfiguration{Variable{"?t1"}, Variable{"?t2"}},
        leftChild, std::nullopt};

    auto clone = tensorIndex.clone();
    ASSERT_TRUE(clone);
    const auto& cloneReference = *clone;
    EXPECT_EQ(typeid(tensorIndex), typeid(cloneReference));
    EXPECT_EQ(cloneReference.getDescriptor(), tensorIndex.getDescriptor());

    EXPECT_NE(tensorIndex.getChildren().at(0),
              cloneReference.getChildren().at(0));
  }

  {
    TensorIndex tensorIndex{
        qec, TensorIndexConfiguration{Variable{"?t1"}, Variable{"?t2"}},
        std::nullopt, rightChild};

    auto clone = tensorIndex.clone();
    ASSERT_TRUE(clone);
    const auto& cloneReference = *clone;
    EXPECT_EQ(typeid(tensorIndex), typeid(cloneReference));
    EXPECT_EQ(cloneReference.getDescriptor(), tensorIndex.getDescriptor());

    EXPECT_NE(tensorIndex.getChildren().at(0),
              cloneReference.getChildren().at(0));
  }

  {
    TensorIndex tensorIndex{
        qec, TensorIndexConfiguration{Variable{"?t1"}, Variable{"?t2"}},
        leftChild, rightChild};

    auto clone = tensorIndex.clone();
    ASSERT_TRUE(clone);
    const auto& cloneReference = *clone;
    EXPECT_EQ(typeid(tensorIndex), typeid(cloneReference));
    EXPECT_EQ(cloneReference.getDescriptor(), tensorIndex.getDescriptor());

    EXPECT_NE(tensorIndex.getChildren().at(0),
              cloneReference.getChildren().at(0));
    EXPECT_NE(tensorIndex.getChildren().at(1),
              cloneReference.getChildren().at(1));
  }
}

}  // namespace stringRepresentation
}  // anonymous namespace
