
#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include <s2/s2earth.h>
#include <s2/s2point.h>
#include <s2/s2polyline.h>

#include <cstdlib>
#include <fstream>
#include <regex>
#include <thread>
#include <variant>

#include "../util/GTestHelpers.h"
#include "../util/IndexTestHelpers.h"
#include "../util/RuntimeParametersTestHelpers.h"
#include "TensorSearchTestHelpers.h"
#include "TensorTestHelpers.h"
#include "engine/ExportQueryExecutionTrees.h"
#include "engine/IndexScan.h"
#include "engine/QueryExecutionTree.h"
#include "engine/TensorSearch.h"
#include "engine/TensorSearchCachedIndex.h"
#include "engine/TensorSearchConfig.h"
#include "index/vocabulary/VocabularyType.h"
#include "libqlever/Qlever.h"
#include "parser/SparqlParser.h"
#include "rdfTypes/Variable.h"

namespace variableColumnMapAndResultWidth {
using namespace TensorSearchTestHelpers;

// Represents from left to right: leftSideBigChild, rightSideBigChild,
// addLeftChildFirst, testVarToColMap
using VarColTestSuiteParam = std::tuple<bool, bool, bool, bool>;

// Internal testing shorthands
using V = Variable;
using VarToColVec = std::vector<std::pair<V, ColumnIndexAndTypeInfo>>;
// Helper function to create a tensor search from VALUEs
std::shared_ptr<TensorSearch> makeTensorSearchFromValues(
    QueryExecutionContext* qec, PayloadVariables pv = PayloadVariables::all(),
    TensorSearchAlgorithm alg = TENSOR_SEARCH_DEFAULT_ALGORITHM) {
  EncodedIriManager encodedIriManager;
  const auto sharedHandle =
      std::make_shared<ad_utility::CancellationHandle<>>();
  // also include some garbage input geometries
  auto pqLeft = SparqlParser::parseQuery(
      &encodedIriManager,
      R"(PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
      SELECT ?a {VALUES 
      (?a) {("{\"data\":[1.0,0,0],\"shape\":[3],\"type\":\"float64\"}"^^dt:DataTensor)}})");
  auto pqRight = SparqlParser::parseQuery(
      &encodedIriManager,
      R"(PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
      SELECT ?b {VALUES
      (?b) {("{\"data\":[0,1.0,0],\"shape\":[3],\"type\":\"float64\"}"^^dt:DataTensor)}})");
  QueryPlanner qp{qec, sharedHandle};

  auto leftChild =
      std::make_shared<QueryExecutionTree>(qp.createExecutionTree(pqLeft));
  auto rightChild =
      std::make_shared<QueryExecutionTree>(qp.createExecutionTree(pqRight));

  std::shared_ptr<QueryExecutionTree> tensorSearchOperation =
      ad_utility::makeExecutionTree<TensorSearch>(
          qec,
          TensorSearchConfiguration{Variable{"?a"}, Variable{"?b"},
                                    std::nullopt, pv, alg},
          std::nullopt, std::nullopt);
  std::shared_ptr<Operation> op = tensorSearchOperation->getRootOperation();
  TensorSearch* tensorSearch = static_cast<TensorSearch*>(op.get());
  auto tensorSearch1 = tensorSearch->addChild(leftChild, Variable{"?a"});
  tensorSearch = static_cast<TensorSearch*>(tensorSearch1.get());
  auto tensorSearch2 = tensorSearch->addChild(rightChild, Variable{"?b"});
  return tensorSearch2;
}

class TensorSearchVarColParamTest
    : public ::testing::TestWithParam<VarColTestSuiteParam> {
 public:
  // Helper function to construct a child for testing
  std::shared_ptr<QueryExecutionTree> getChild(QueryExecutionContext* qec,
                                               bool getBigChild,
                                               std::string numberOfChild) {
    std::string obja = absl::StrCat("?obja", numberOfChild);
    std::string objb = absl::StrCat("?objb", numberOfChild);
    std::string name = absl::StrCat("?name", numberOfChild);
    std::string t = absl::StrCat("?t", numberOfChild);
    if (getBigChild) {
      return buildMediumChild(qec, {obja, std::string{"<rel>"}, objb},
                              {objb, std::string{"<name>"}, name},
                              {objb, std::string{"<p1>"}, t}, obja, objb);
    } else {
      return buildSmallChild(qec, {obja, std::string{"<p1>"}, t},
                             {obja, std::string{"<name>"}, name}, obja);
    }
  }

  // Helper function to construct a vector of the expected columns in the
  // example child generated by getChild
  std::vector<std::pair<std::string, std::string>> addExpectedColumns(
      std::vector<std::pair<std::string, std::string>> expectedColumns,
      bool bigChild, std::string numberOfChild) {
    std::string obja = absl::StrCat("?obja", numberOfChild);
    std::string objb = absl::StrCat("?objb", numberOfChild);
    std::string name = absl::StrCat("?name", numberOfChild);
    std::string t = absl::StrCat("?t", numberOfChild);
    expectedColumns.push_back({obja, "<"});
    expectedColumns.push_back({t, "\"{"});
    if (bigChild) {
      expectedColumns.push_back({objb, "<"});
    }
    return expectedColumns;
  };

  std::shared_ptr<TensorSearch> makeTensorSearch(
      QueryExecutionContext* qec, VarColTestSuiteParam parameters,
      bool addDist = true, PayloadVariables pv = PayloadVariables::all(),
      TensorSearchAlgorithm alg = TENSOR_SEARCH_DEFAULT_ALGORITHM,
      TensorDistanceAlgorithm distAlg = TENSOR_SEARCH_DEFAULT_DISTANCE) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto leftChild = getChild(qec, leftSideBigChild, "1");
    auto rightChild = getChild(qec, rightSideBigChild, "2");

    std::optional<Variable> dist = std::nullopt;
    if (addDist) {
      dist = Variable{"?dist"};
    }
    std::shared_ptr<QueryExecutionTree> tensorSearchOperation =
        ad_utility::makeExecutionTree<TensorSearch>(
            qec,
            TensorSearchConfiguration{Variable{"?t1"}, Variable{"?t2"}, dist,
                                      pv, alg, distAlg},
            std::nullopt, std::nullopt);
    std::shared_ptr<Operation> op = tensorSearchOperation->getRootOperation();
    TensorSearch* tensorSearch = static_cast<TensorSearch*>(op.get());
    auto firstChild = addLeftChildFirst ? leftChild : rightChild;
    auto secondChild = addLeftChildFirst ? rightChild : leftChild;
    Variable firstVariable =
        addLeftChildFirst ? Variable{"?t1"} : Variable{"?t2"};
    Variable secondVariable =
        addLeftChildFirst ? Variable{"?t2"} : Variable{"?t1"};
    auto tensorSearch1 = tensorSearch->addChild(firstChild, firstVariable);
    tensorSearch = static_cast<TensorSearch*>(tensorSearch1.get());
    auto tensorSearch2 = tensorSearch->addChild(secondChild, secondVariable);
    return tensorSearch2;
  }

  // only test one at a time. Then the gtest will fail on the test, which
  // failed, instead of failing for both getResultWidth() and
  // computeVariableToColumnMap() if only one of them is wrong
  void testGetResultWidthOrVariableToColumnMap(
      VarColTestSuiteParam parameters,
      TensorSearchAlgorithm alg = TENSOR_SEARCH_DEFAULT_ALGORITHM) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto qec = buildQec(makeVectorKg(6, 6));
    auto tensorSearchOp =
        makeTensorSearch(qec, parameters, true, PayloadVariables::all(), alg);
    auto tensorSearch = static_cast<TensorSearch*>(tensorSearchOp.get());

    auto numTriples = qec->getIndex().numTriples().normal;
    ASSERT_EQ(numTriples, 6);

    if (!testVarToColMap) {
      // size_t expectedResultWidth =
      //     (leftSideBigChild ? 4 : 3) + (rightSideBigChild ? 4 : 3) + 1;
      // ASSERT_EQ(tensorSearch->getResultWidth(), expectedResultWidth);
    } else {
      std::vector<std::pair<std::string, std::string>> expectedColumns{};

      expectedColumns =
          addExpectedColumns(expectedColumns, leftSideBigChild, "1");
      expectedColumns =
          addExpectedColumns(expectedColumns, rightSideBigChild, "2");

      expectedColumns.push_back({"?dist", "0"});

      auto varColMap = tensorSearch->computeVariableToColumnMap();
      auto resultTable = tensorSearch->computeResult(false);

      // if the size of varColMap and expectedColumns is the same and each
      // element of expectedColumns is contained in varColMap, then they are the
      // same (assuming that each element is unique)
      ASSERT_EQ(varColMap.size(), expectedColumns.size());

      for (size_t i = 0; i < expectedColumns.size(); i++) {
        ASSERT_TRUE(varColMap.contains(Variable{expectedColumns.at(i).first}));

        // test, that the column contains the correct values
        ColumnIndex ind =
            varColMap[Variable{expectedColumns.at(i).first}].columnIndex_;
        const IdTable* r = &resultTable.idTable();
        ASSERT_LT(0, r->numRows());
        ASSERT_LT(ind, r->numColumns());
        ValueId tableEntry = r->at(0, ind);

        auto [value, type] = ExportQueryExecutionTrees::idToStringAndType(
                                 qec->getIndex(), tableEntry, {})
                                 .value();
        if (tableEntry.getDatatype() == Datatype::VocabIndex) {
          ASSERT_TRUE(value.find(expectedColumns.at(i).second, 0) !=
                      std::string::npos);
        }
      }
    }
  }

  // Test tensor search on contains
  void testGetResultWidthOrVariableToColumnMapTensorSearchContains(
      VarColTestSuiteParam parameters) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    auto qec = buildQec(makeVectorKg(6, 6));

    auto tensorSearch =
        makeTensorSearch(qec, parameters, false, PayloadVariables::all(),
                         TensorSearchAlgorithm::NAIVE,
                         TensorDistanceAlgorithm::COSINE_SIMILARITY);
    auto tensorSearchPtr = static_cast<TensorSearch*>(tensorSearch.get());

    auto numTriples = qec->getIndex().numTriples().normal;
    ASSERT_EQ(numTriples, 6);

    if (!testVarToColMap) {
      // size_t expectedResultWidth =
      //     (leftSideBigChild ? 4 : 3) + (rightSideBigChild ? 4 : 3) + 1;
      // ASSERT_EQ(tensorSearch->getResultWidth(), expectedResultWidth);
    } else {
      std::vector<std::pair<std::string, std::string>> expectedColumns{};

      expectedColumns =
          addExpectedColumns(expectedColumns, leftSideBigChild, "1");
      expectedColumns =
          addExpectedColumns(expectedColumns, rightSideBigChild, "2");

      auto varColMap = tensorSearch->computeVariableToColumnMap();
      auto resultTable = tensorSearch->computeResult(false);

      // if the size of varColMap and expectedColumns is the same and each
      // element of expectedColumns is contained in varColMap, then they are the
      // same (assuming that each element is unique)
      ASSERT_EQ(varColMap.size(), expectedColumns.size());

      for (size_t i = 0; i < expectedColumns.size(); i++) {
        ASSERT_TRUE(varColMap.contains(Variable{expectedColumns.at(i).first}));

        // test, that the column contains the correct values
        ColumnIndex ind =
            varColMap[Variable{expectedColumns.at(i).first}].columnIndex_;
        const IdTable* r = &resultTable.idTable();
        ASSERT_LT(0, r->numRows());
        ASSERT_LT(ind, r->numColumns());

        auto col = r->getColumn(ind);
        std::vector<std::string> columnEntries;
        columnEntries.reserve(r->numRows());
        for (const auto& valueId : col) {
          auto [value, type] = ExportQueryExecutionTrees::idToStringAndType(
                                   qec->getIndex(), valueId, {})
                                   .value();
          if (type == TENSOR_LITERAL || type == TENSOR_NUMERIC_LITERAL) {
            value = absl::StrCat("\"", value, "\"^^<", type, ">");
          }
          columnEntries.push_back(value);
        }

        auto expected = expectedColumns.at(i).second;
        EXPECT_THAT(columnEntries,
                    ::testing::Contains(::testing::StartsWith(expected)));
      }
    }
  }

  // Function to test the variable to column map that is generated by spatial
  // join with the left and right children as given by the parameters. It will
  // try all possible, valid payloadVariables settings and check the variable
  // to column maps using a comprehensible and easy to debug string
  // representation.
  void testPayloadVariablesVarToColMap(VarColTestSuiteParam parameters) {
    auto [leftSideBigChild, rightSideBigChild, addLeftChildFirst,
          testVarToColMap] = parameters;
    if (!testVarToColMap) {
      return;
    }

    auto computeAndCompareVarToColMaps =
        [&](bool addDist, PayloadVariables pv,
            VariableToColumnMap expectedVarToColMap,
            std::optional<std::string> matchWarning = std::nullopt) {
          auto qec = buildQec(makeVectorKg(6, 6));
          auto tensorSearchOp = makeTensorSearch(qec, parameters, addDist, pv);
          auto tensorSearch = static_cast<TensorSearch*>(tensorSearchOp.get());
          auto vc = tensorSearch->computeVariableToColumnMap();
          ASSERT_THAT(
              vc, ::testing::UnorderedElementsAreArray(expectedVarToColMap));
          if (matchWarning) {
            ASSERT_THAT(tensorSearch->collectWarnings(),
                        ::testing::Contains(
                            ::testing::HasSubstr(matchWarning.value())));
          }
        };

    // Expected variables
    V obja{"?obja"};
    V objb{"?objb"};
    V t{"?t"};
    V name{"?name"};
    V distVar{"?dist"};
    std::vector<V> smallChild{obja, objb, t};
    std::vector<V> bigChild{obja, objb, t, name};

    auto makeExpected = [&](bool leftSideBigChild, bool rightSideBigChild,
                            bool addDist, bool withObj,
                            bool withTensor) -> VariableToColumnMap {
      size_t currentColumn = 0;
      VariableToColumnMap expected;

      auto addV = [&](std::vector<V> vec, bool right = false) {
        for (auto v : vec) {
          if (right && ((v == obja && !withObj) || (v == t && !withTensor))) {
            continue;
          }
          V expectedVar{absl::StrCat(v.name(), right ? "2" : "1")};
          expected[expectedVar] = ColumnIndexAndTypeInfo{
              currentColumn,
              ColumnIndexAndTypeInfo::UndefStatus::AlwaysDefined};
          currentColumn++;
        }
      };

      addV(leftSideBigChild ? bigChild : smallChild);
      addV({V{"?t"}});
      addV(rightSideBigChild ? bigChild : smallChild, true);
      addV({V{"?t"}}, true);
      if (addDist) {
        expected[distVar] = ColumnIndexAndTypeInfo{
            currentColumn,
            ColumnIndexAndTypeInfo::UndefStatus::PossiblyUndefined};
      }
      return expected;
    };

    std::vector<bool> bools{true, false};
    for (bool withObj : bools) {
      for (bool withTensor : bools) {
        for (bool addDist : bools) {
          std::vector<Variable> payloadVars;
          if (withObj) {
            payloadVars.push_back(Variable{"?obja2"});
          }
          if (withTensor) {
            payloadVars.push_back(Variable{"?t2"});
          }

          // Test the regular and valid payloadVars
          auto exp = makeExpected(leftSideBigChild, rightSideBigChild, addDist,
                                  withObj, withTensor);
          computeAndCompareVarToColMaps(addDist, payloadVars, exp);

          // Also test the PayloadAllVariables version
          if (withTensor && withObj && (!rightSideBigChild)) {
            computeAndCompareVarToColMaps(addDist, PayloadVariables::all(),
                                          exp);
          }

          // Test multiple occurrences of variables
          if (withObj) {
            payloadVars.push_back(Variable{"?obja2"});
            // Variable ?obja2 is now contained twice
            computeAndCompareVarToColMaps(addDist, payloadVars, exp);
            payloadVars.pop_back();
          }

          // Test contained right variable in payloadVars
          payloadVars.push_back(Variable{"?t2"});
          computeAndCompareVarToColMaps(addDist, payloadVars, exp);
          payloadVars.pop_back();

          // Test warnings for unbound variables
          payloadVars.push_back(Variable{"?t1"});
          computeAndCompareVarToColMaps(
              addDist, payloadVars, exp,
              "Variable '?t1' selected as payload to "
              "tensor search but not present in right child");
          payloadVars.pop_back();

          payloadVars.push_back(Variable{"?obja1"});
          computeAndCompareVarToColMaps(
              addDist, payloadVars, exp,
              "Variable '?obja1' selected as payload to "
              "tensor search but not present in right child");
          payloadVars.pop_back();

          payloadVars.push_back(Variable{"?isThereSomebodyHere"});
          computeAndCompareVarToColMaps(
              addDist, payloadVars, exp,
              "Variable '?isThereSomebodyHere' selected as payload to "
              "tensor search but not present in right child");
          payloadVars.pop_back();

          // Test if distance variable contained
          if (addDist) {
            payloadVars.push_back(distVar);
            computeAndCompareVarToColMaps(
                addDist, payloadVars, exp,
                "Variable '?dist' selected "
                "as payload to tensor search but not present in right "
                "child");
            payloadVars.pop_back();
          }
        }
      }
    }
  }
};

TEST_P(TensorSearchVarColParamTest, variableToColumnMap) {
  testGetResultWidthOrVariableToColumnMap(GetParam());
}

// Test `libtensorsearch` with `within-dist` tensor search type. This is
// essentially a self-join (but the payload may be different for the two
// sides).
TEST_P(TensorSearchVarColParamTest, variableToColumnMapLibtensorsearch) {
  testGetResultWidthOrVariableToColumnMap(GetParam(),
                                          TensorSearchAlgorithm::ANNOY);
}

// Test `libtensorsearch` with `contains` tensor search type. Here the two sides
// have different sets of objects,
TEST_P(TensorSearchVarColParamTest,
       variableToColumnMapLibtensorsearchContains) {
  testGetResultWidthOrVariableToColumnMapTensorSearchContains(GetParam());
}

// Test a tensor search with VALUES as both children
TEST(TensorSearchVarColParamTest, testTensorsearchFromvalues) {
  auto qec = buildQec(TensorSearchTestHelpers::makeVectorKg(6, 6));

  auto tensorSearch = makeTensorSearchFromValues(qec, PayloadVariables::all(),
                                                 TensorSearchAlgorithm::NAIVE);
  auto tensorSearch_ptr = static_cast<TensorSearch*>(tensorSearch.get());

  auto resultTable = tensorSearch_ptr->computeResult(false);
  ASSERT_EQ(resultTable.idTable().numRows(), 1);
}

TEST_P(TensorSearchVarColParamTest, payloadVariables) {
  testPayloadVariablesVarToColMap(GetParam());
}

INSTANTIATE_TEST_SUITE_P(TensorSearch, TensorSearchVarColParamTest,
                         ::testing::Combine(::testing::Bool(),
                                            ::testing::Bool(),
                                            ::testing::Bool(),
                                            ::testing::Bool()));

}  // namespace variableColumnMapAndResultWidth
