# Copyright 2026 The QLever Authors, in particular:
#
# 2026 Johannes Kalmbach <kalmbach@cs.uni-freiburg.de>, UFR
#
# UFR = University of Freiburg, Chair of Algorithms and Data Structures
#
# You may not use this file except in compliance with the Apache 2.0 License,
# which can be found in the `LICENSE` file at the root of the QLever project.

"""Generation of `CompilationInfo.cpp`, the Bazel counterpart of `CompilationInfo.cmake`.

The generated file consists of the definitions of four macros followed by the
template `CompilationInfo.cpp.in`, which is where the interesting part lives.
The values of the macros come from the workspace status (see
`workspace_status.sh`), which Bazel is the only one allowed to look at: a rule
may not run `git` itself, because that would make the build depend on state that
Bazel cannot track.
"""

# The macros that are prepended to the template, as
# `(macro name, status key, status file, fallback)`. The status file is either
# `stable` or `volatile`; a value from the volatile file does not force the
# dependents to be rebuilt when it changes, which is what we want for the
# compilation time. A key that is missing, which is the case when Bazel runs
# without `--workspace_status_command`, falls back to a placeholder so that the
# build still works.
_MACROS = [
    ("QLEVER_GIT_HASH_STR", "STABLE_QLEVER_GIT_HASH", "stable", "git hash not available"),
    ("QLEVER_PROJECT_VERSION_STR", "STABLE_QLEVER_PROJECT_VERSION", "stable", "project version not available"),
    ("QLEVER_DATETIME_OF_COMPILATION_STR", "QLEVER_DATETIME_OF_COMPILATION", "volatile", "datetime of compilation not available"),
    ("QLEVER_TIME_OF_COMPILATION_UNIX_STR", "QLEVER_TIME_OF_COMPILATION_UNIX", "volatile", "0"),
]

# `$1` is the stable status file, `$2` the volatile one, `$3` the template and
# `$4` the output. The `sed` call escapes the value for use inside a C++ string
# literal.
_PREAMBLE = """\
set -eu
status_value() {
  value="$(sed -n "s/^$2 //p" "$1" | head -n 1)"
  if [ -z "${value}" ]; then
    value="$3"
  fi
  printf '%s' "${value}" | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g'
}
{
  printf '// Generated by //bazel:compilation_info.bzl. Do not edit.\\n'
"""

_EPILOGUE = """\
  cat "$3"
} > "$4"
"""

def _generate_command():
    """Return the shell script of the generating action."""
    lines = [_PREAMBLE]
    for macro, key, status_file, fallback in _MACROS:
        status_argument = "$1" if status_file == "stable" else "$2"
        lines.append(
            '  printf \'#define %s "%%s"\\n\' "$(status_value %s %s \'%s\')"\n' %
            (macro, status_argument, key, fallback),
        )
    lines.append(_EPILOGUE)
    return "".join(lines)

def _compilation_info_impl(ctx):
    output = ctx.actions.declare_file(ctx.attr.name + ".cpp")
    ctx.actions.run_shell(
        outputs = [output],
        inputs = [ctx.info_file, ctx.version_file, ctx.file._template],
        arguments = [
            ctx.info_file.path,
            ctx.version_file.path,
            ctx.file._template.path,
            output.path,
        ],
        command = _generate_command(),
        mnemonic = "QLeverCompilationInfo",
        progress_message = "Generating %s" % output.short_path,
        # The action reads the workspace status, which is not part of the action
        # key, so its result must not be shared with other machines.
        execution_requirements = {"no-remote-cache": "1"},
    )
    return [DefaultInfo(files = depset([output]))]

compilation_info = rule(
    implementation = _compilation_info_impl,
    attrs = {
        "_template": attr.label(
            default = Label("//bazel:CompilationInfo.cpp.in"),
            allow_single_file = True,
        ),
    },
    doc = """Generate the `CompilationInfo.cpp` that defines the constants of `CompilationInfo.h`.

The output is named `<name>.cpp` and is meant to be the single source of a
`cc_library`; see `//src:compilationInfo`.""",
)
