# Copyright 2026 The QLever Authors, in particular:
#
# 2026 Johannes Kalmbach <kalmbach@cs.uni-freiburg.de>, UFR
#
# UFR = University of Freiburg, Chair of Algorithms and Data Structures
#
# You may not use this file except in compliance with the Apache 2.0 License,
# which can be found in the `LICENSE` file at the root of the QLever project.

"""Repository rule that exposes a system library found via `pkg-config`.

This is the Bazel counterpart of the `find_package` and `pkg_check_modules`
calls in the top-level `CMakeLists.txt`. It is used for the heavy C libraries
that QLever does not vendor: ICU, OpenSSL, zstd, jemalloc and liburing.

For each library, `pkg-config` is queried for its include directories and its
linker flags. Include directories that the C++ toolchain already searches by
default (`/usr/include` and friends) are not declared again; any other
directory (for example a Homebrew or Conan prefix) is symlinked into the
generated repository so that the headers are visible inside the Bazel sandbox.

A library can be declared optional, mirroring the CMake behavior for jemalloc
and io_uring. An optional library that `pkg-config` cannot find degrades to an
empty `cc_library`, so that dependents keep building; in that case the
`defines_if_found` are not set, which is how `QLEVER_HAS_IO_URING` ends up
undefined exactly when there is no `liburing`.
"""

# Include directories that every C/C++ toolchain searches anyway. Headers in
# these directories must not be declared as inputs, because they are covered by
# the toolchain's `cxx_builtin_include_directories`.
_DEFAULT_INCLUDE_DIRS = [
    "/usr/include",
    "/usr/local/include",
]

def _run(rctx, arguments):
    """Run a command and return `(success, stdout)` with `stdout` stripped."""
    result = rctx.execute(arguments)
    return result.return_code == 0, result.stdout.strip()

def _pkg_config_system_library_impl(rctx):
    pkg_config = rctx.which("pkg-config")
    modules = list(rctx.attr.modules)

    found = pkg_config != None
    include_flags = ""
    link_flags = ""
    if found:
        found, include_flags = _run(rctx, [pkg_config, "--cflags-only-I"] + modules)
    if found:
        found, link_flags = _run(rctx, [pkg_config, "--libs"] + modules)

    if not found:
        if rctx.attr.required:
            fail(
                ("The system library `%s` is required, but `pkg-config` could not " +
                 "find the module(s) %s. Install the corresponding development " +
                 "package (on Ubuntu, `apt install %s`), or point " +
                 "`PKG_CONFIG_PATH` at it.") % (
                    rctx.attr.library_name,
                    ", ".join(["`%s`" % module for module in modules]),
                    rctx.attr.ubuntu_package,
                ),
            )

        # The optional case: an empty library, so that dependents still build.
        rctx.file("BUILD.bazel", _EMPTY_BUILD_TEMPLATE.format(name = rctx.attr.library_name))
        return

    # Make the include directories that the toolchain does not search by
    # default visible inside the sandbox by symlinking them into this
    # repository.
    include_directory_names = []
    for flag in include_flags.split(" "):
        directory = flag[len("-I"):].strip()
        if not directory or directory in _DEFAULT_INCLUDE_DIRS:
            continue
        name = "include_%d" % len(include_directory_names)
        rctx.symlink(directory, name)
        include_directory_names.append(name)

    rctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        name = rctx.attr.library_name,
        hdrs = repr([name + "/**" for name in include_directory_names]),
        includes = repr(include_directory_names),
        linkopts = repr([flag for flag in link_flags.split(" ") if flag]),
        defines = repr(list(rctx.attr.defines_if_found)),
    ))

_EMPTY_BUILD_TEMPLATE = """\
# Generated by `//bazel:system_library.bzl`. Do not edit.
# `pkg-config` did not find this optional library, so it is empty.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "{name}",
    visibility = ["//visibility:public"],
)
"""

_BUILD_TEMPLATE = """\
# Generated by `//bazel:system_library.bzl`. Do not edit.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "{name}",
    hdrs = glob({hdrs}, allow_empty = True),
    defines = {defines},
    includes = {includes},
    linkopts = {linkopts},
    visibility = ["//visibility:public"],
)
"""

pkg_config_system_library = repository_rule(
    implementation = _pkg_config_system_library_impl,
    attrs = {
        "defines_if_found": attr.string_list(
            doc = "Preprocessor definitions to set, but only if the library was found.",
        ),
        "library_name": attr.string(
            mandatory = True,
            doc = """The name of the generated `cc_library`.

This cannot be derived from `name`, because inside a module extension that is
the canonical repository name (`+qlever_system+icu`) rather than the apparent
one (`icu`).""",
        ),
        "modules": attr.string_list(
            mandatory = True,
            doc = "The `pkg-config` module name(s) to query.",
        ),
        "required": attr.bool(
            default = True,
            doc = "Whether a missing library is an error or degrades to an empty library.",
        ),
        "ubuntu_package": attr.string(
            doc = "The Ubuntu package that provides the library, used in the error message.",
        ),
    },
    configure = True,
    environ = ["PATH", "PKG_CONFIG_PATH", "PKG_CONFIG_LIBDIR"],
    local = True,
)

# The system libraries that QLever uses. The `required` flag mirrors the CMake
# build: ICU (unless `--//bazel:no_unicode`), OpenSSL and zstd are hard
# requirements there, jemalloc and io_uring are optional.
_SYSTEM_LIBRARIES = [
    struct(
        name = "icu",
        modules = ["icu-uc", "icu-i18n"],
        required = False,
        ubuntu_package = "libicu-dev",
        defines_if_found = [],
    ),
    struct(
        name = "openssl",
        modules = ["openssl"],
        required = True,
        ubuntu_package = "libssl-dev",
        defines_if_found = [],
    ),
    struct(
        name = "zstd",
        modules = ["libzstd"],
        required = True,
        ubuntu_package = "libzstd-dev",
        defines_if_found = [],
    ),
    struct(
        name = "jemalloc",
        modules = ["jemalloc"],
        required = False,
        ubuntu_package = "libjemalloc-dev",
        defines_if_found = [],
    ),
    struct(
        name = "liburing",
        modules = ["liburing"],
        required = False,
        ubuntu_package = "liburing-dev",
        # This is the `QLEVER_HAS_IO_URING` of the `USE_IO_URING` block in
        # `CMakeLists.txt`: defined exactly when `liburing` was found.
        defines_if_found = ["QLEVER_HAS_IO_URING"],
    ),
]

def _qlever_system_impl(_module_ctx):
    for library in _SYSTEM_LIBRARIES:
        pkg_config_system_library(
            name = library.name,
            library_name = library.name,
            modules = library.modules,
            required = library.required,
            ubuntu_package = library.ubuntu_package,
            defines_if_found = library.defines_if_found,
        )

qlever_system = module_extension(
    implementation = _qlever_system_impl,
    doc = "Declares the system libraries that QLever takes via `pkg-config`.",
)
