# Usage:
# - Install pre-commit: `pip install pre-commit` (once).ci:
# - In the main directory of QLever run `pre-commit install`
# - Each git commit will now automatically be formatted. Note that
# - commits will fail if the hook reformats your files, so you
# - have to run git commit twice in order to first format and then
# - actually commit.
# To use your local clang-format-16:
# - comment out the hook from https://github.com/pre-commit/mirrors-clang-format
# - comment in the local hook
# - run `pre-commit install`
repos:
  # Uses a packaged version of clang-format from https://github.com/ssciwr/clang-format-wheel
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
      - id: clang-format
        'types_or': [ c++, c ]
    # Uses the local clang-format
#  - repo: local
#    hooks:
#      # Inspired by https://github.com/doublify/pre-commit-clang-format and
#      # https://github.com/pre-commit/mirrors-clang-format
#      - id: clang-format-16
#        name: clang-format
#        description: Format files with ClangFormat16.
#        entry: clang-format-16 -i
#        language: system
#        'types_or': [ c++, c ]
#        args: [ "-style=file" ]
#        require_serial: false
