# Usage:
# - Install pre-commit: `pip install pre-commit` (once).ci:
# - In the main directory of QLever run
#   - `pre-commit install` to use a package version of clang-format
#   - `pre-commit install -c .pre-commit-config-local.yaml` to use the local clang-format
# - Each git commit will now automatically be formatted. Note that
# - commits will fail if the hook reformats your files, so you
# - have to run git commit twice in order to first format and then
# - actually commit.
repos:
  # Uses a packaged version of clang-format from https://github.com/ssciwr/clang-format-wheel
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
      - id: clang-format
        'types_or': [ c++, c ]

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in .codespellrc
    rev: v2.2.6
    hooks:
    - id: codespell
