add_subdirectory(ConfigManager)
add_subdirectory(MemorySize)
add_subdirectory(http)
add_library(stringUtils StringUtils.cpp)
qlever_target_link_libraries(stringUtils)

add_library(antlrErrorHandling antlr/ANTLRErrorHandling.cpp antlr/GenerateAntlrExceptionMetadata.cpp ParseException.cpp)
qlever_target_link_libraries(antlrErrorHandling stringUtils antlr4_umbrella)
add_library(qlever_util ParseableDuration.cpp UnitOfMeasurement.cpp Conversions.cpp Date.cpp DateYearDuration.cpp Duration.cpp CancellationHandle.cpp LazyJsonParser.cpp BlankNodeManager.cpp IoUringManager.cpp FilesystemHelpers.cpp QueryEventLog.cpp ResourceMonitor.cpp)
qlever_target_link_libraries(qlever_util antlrErrorHandling s2 pb_util pb_util_geo pb_util_json rdfTypes antlr4_umbrella)

add_subdirectory(metrics)
