
add_executable(AlgorithmBackportTests algorithmTest.cpp)
add_executable(DebugJoinView DebugJoinView.cpp)
qlever_target_link_libraries(DebugJoinView)
qlever_target_link_libraries(AlgorithmBackportTests qleverTestMain GTest::gtest GTest::gmock)
gtest_discover_tests(AlgorithmBackportTests AlgorithmBackportTests)
addLinkAndDiscoverTestNoLibs(ConceptsTest)
addLinkAndDiscoverTestNoLibs(ShiftTest)
addLinkAndDiscoverTestNoLibs(ValueIdentityTest)
addLinkAndDiscoverTestNoLibs(BackportIteratorTest)
addLinkAndDiscoverTestNoLibs(StartsWithTest)
addLinkAndDiscoverTestNoLibs(EndsWithTest)
addLinkAndDiscoverTestNoLibs(FunctionalTest)
addLinkAndDiscoverTestNoLibs(ThreeWayComparisonTest)
addLinkAndDiscoverTestNoLibs(AtomicFlagTest)
