add_subdirectory(data)

addLinkAndDiscoverTest(AsyncBlockSourceTest sparqlParser)
addLinkAndDiscoverTest(LiteralOrIriTest engine)
addLinkAndDiscoverTest(PayloadVariablesTest engine)
addLinkAndDiscoverTest(QuadTest engine)
addLinkAndDiscoverTest(BlankNodeExpressionTest engine)
addLinkAndDiscoverTest(PropertyPathTest sparqlParser)
addLinkAndDiscoverTest(UpdateTriplesTest sparqlParser)
addLinkAndDiscoverTest(NamedCachedResultTest sparqlParser)
addLinkAndDiscoverTest(GraphPatternOperationTest sparqlParser)
addLinkAndDiscoverTest(GraphPatternAnalysisTest sparqlParser)
addLinkAndDiscoverTest(SparqlAntlrParserTest sparqlParser engine)
addLinkAndDiscoverTest(SparqlAntlrParserUpdateTest sparqlParser engine)
addLinkAndDiscoverTest(SparqlAntlrParserExpressionTest sparqlParser sparqlExpressions engine)

