name: Format check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          # The version in the default Ubuntu repositories is too old (and has some breaking changes),
          # so we install from the official LLVM repository.
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt install -y clang-format-18

      - name: Run the format checker
        run: ${{github.workspace}}/misc/format-check.sh
