name: Format check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run:  sudo apt install -y clang-format-18

      - name: Run the format checker
        run: ${{github.workspace}}/misc/format-check.sh

