name: Install dependencies ubuntu
on:
  workflow_call:

jobs:
  install_dependencies:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run:  |
          sudo gem install apt-spy2 && sudo apt-spy2 fix --commit --launchpad --country=US
          sudo apt-get update
          sudo apt-get install -y libicu-dev tzdata gcc-10 libzstd-dev libjemalloc-dev
      - name: Install boost from PPa
        run: sudo add-apt-repository -y ppa:mhier/libboost-latest && sudo apt update && sudo apt install -y libboost1.81-all-dev libboost-url1.81-dev
