name: sonarcloud-analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Save PR number and sonarcloud data in same directory
      if: github.event_name == 'pull_request'
      # Note: If you change any of the filenames here, you also have to change them in `upload-coverage.yml`
      run : |
        mkdir -p sonarcloud-report
        echo ${{ github.event.number }} > ./sonarcloud-report/pr
        echo ${{ github.repository }} > ./sonarcloud-report/github_repository
        echo ${GITHUB_REF} > ./sonarcloud-report/github_ref
    - name: Upload sonarcloud artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: sonarcloud-report
        path: sonarcloud-report/
    # Note: for now we do not run the e2e tests for the coverage check

