name: sparql-test-suite

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
          compiler: clang
          compiler-version: 16
          build-type: Release
          cmake-flags: "-DCMAKE_C_COMPILER=clang-16 -DCMAKE_CXX_COMPILER=clang++-16"

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
        path: qlever-code
    - name: Checkout sparql-test-suite-files
      uses: actions/checkout@v3
      with:
        repository: "w3c/rdf-tests"
        path: sparql-test-suite
    - name: Checkout qlever-test-suite
      uses: actions/checkout@v3
      with:
        repository: "SIRDNARch/qlever-test-suite"
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: qlever-test-suite
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Install dependencies
      uses: ./qlever-code/.github/workflows/install-dependencies-ubuntu
    - name: Install compiler
      uses: ./qlever-code/.github/workflows/install-compiler-ubuntu
      with:
        compiler: "clang"
        compiler-version: "16"
    - name: Create build directory
      run: mkdir ${{github.workspace}}/qlever-code/build
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/qlever-code/build ${{env.cmake-flags}} -DCMAKE_BUILD_TYPE=${{env.build-type}} -DLOGLEVEL=INFO -DUSE_PARALLEL=false

    - name: Build
      run: cmake --build ${{github.workspace}}/qlever-code/build --config ${{env.build-type}} -- -j $(nproc)
    - name: Execute test suite
      run: |
          python ./qlever-test-suite/testsuite.py config http://0.0.0.0 7001 ./sparql-test-suite-files/sparql/sparql11/ ../qlever-code/build/ listOfTests.csv
          python ./qlever-test-suite/testsuite.py extract
          python3 ./qlever-test-suite/testsuite.py ${{ github.sha }}
