name: sparql-conformance-new

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    continue-on-error: true
    env:
      compiler: clang
      compiler-version: 16
      build-type: Release
      cmake-flags: "-DCMAKE_C_COMPILER=clang-16 -DCMAKE_CXX_COMPILER=clang++-16"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"
          path: qlever-code
      - name: Checkout sparql-test-suite-files
        uses: actions/checkout@v6
        with:
          repository: "w3c/rdf-tests"
          path: sparql-test-suite
          fetch-depth: 1
      - name: Checkout sparql-conformance
        uses: actions/checkout@v6
        with:
          repository: "SIRDNARch/sparql-conformance"
          path: sparql-conformance
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: sparql-conformance/requirements.txt
      - name: Install python dependencies
        run: pip install -r ./sparql-conformance/requirements.txt
      - name: Install dependencies
        uses: ./qlever-code/.github/workflows/install-dependencies-ubuntu
      - name: Install compiler
        uses: ./qlever-code/.github/workflows/install-compiler-ubuntu
        with:
          compiler: "clang"
          compiler-version: "16"
      - name: Create build directory
        run: mkdir ${{github.workspace}}/qlever-code/build
      - name: Configure CMake
        run: cmake -S ${{github.workspace}}/qlever-code/ -B ${{github.workspace}}/qlever-code/build ${{env.cmake-flags}} -DCMAKE_BUILD_TYPE=${{env.build-type}} -DLOGLEVEL=INFO -DUSE_PARALLEL=false
      - name: Build qlever binaries
        run: cmake --build ${{github.workspace}}/qlever-code/build --target qlever-index qlever-server --config ${{env.build-type}} -- -j $(nproc)
      - name: Execute test suite
        working-directory: ${{ github.workspace }}/sparql-conformance
        run: |
          python3 main.py \
            --name ${{ github.sha }} \
            --engine ./src/engines/qlever-binaries-manager.py \
            --binaries-directory ${{ github.workspace }}/qlever-code/build/ \
            --port 7001 \
            --graph-store /http-graph-store \
            --sparql11-dir ${{ github.workspace }}/sparql-test-suite/sparql/sparql11/ \
            --sparql10-dir ${{ github.workspace }}/sparql-test-suite/sparql/sparql10/ \
            --type-alias '[["http://www.w3.org/2001/XMLSchema#int", "http://www.w3.org/2001/XMLSchema#integer"], ["http://www.w3.org/2001/XMLSchema#float", "http://www.w3.org/2001/XMLSchema#double"], ["http://www.w3.org/2001/XMLSchema#decimal", "http://www.w3.org/2001/XMLSchema#double"], ["http://www.w3.org/2001/XMLSchema#decimal", "http://www.w3.org/2001/XMLSchema#float"], ["http://www.w3.org/2001/XMLSchema#string", null]]'
      - name: Save workflow information
        # Note: If you change any of the filenames here, you also have to change them in `sparql-conformance-new-uploader.yml`
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          mkdir -p conformance-report
          echo ${{ github.event_name }} > ./conformance-report/event
          echo ${{ github.event.number }} > ./conformance-report/pr
          echo ${{ github.repository }} > ./conformance-report/github_repository
          echo ${GITHUB_REF} > ./conformance-report/github_ref
          echo "$HEAD_REF" > ./conformance-report/head_ref
      - name: Save SHA and conformance report if it is a master commit.
        if: github.event_name == 'push'
        run: |
          echo ${{github.sha}} > ./conformance-report/sha
          mv ./sparql-conformance/results/${{ github.sha }}.json.bz2 conformance-report/${{ github.sha }}.json.bz2
      - name: Save SHA and conformance report if it is a PR.
        if: github.event_name == 'pull_request'
        run: |
          echo ${{github.event.pull_request.head.sha}} > ./conformance-report/sha
          mv ./sparql-conformance/results/${{ github.sha }}.json.bz2 conformance-report/${{ github.event.pull_request.head.sha }}.json.bz2
      - name: Save SHA and conformance report if it is a merge_group run.
        if: github.event_name == 'merge_group'
        run: |
          echo ${{github.sha}} > ./conformance-report/sha
          mv ./sparql-conformance/results/${{ github.sha }}.json.bz2 conformance-report/${{ github.sha }}.json.bz2
      - name: Upload conformance report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: conformance-report
          path: conformance-report/
